[tool.poetry]
name = "aithena-services"
version = "0.1.0"
description = ""
authors = ["Camilo Velez <camilo.velez@axleinfo.com>, Antoine Gerardin <antoine.gerardin@nextonicsolutions.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.7.4"
openai = "^1.35.13"
requests = "^2.32.3"
llama-index-llms-ollama = "^0.2.2"
llama-index = "^0.10.65"
llama-index-llms-openai = "^0.1.29"
llama-index-embeddings-ollama = "^0.1.3"
fastapi = {extras = ["standard"], version = "^0.112.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
